# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '百思' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod "MJRefresh"

  # Pods for 百思

  target '百思Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '百思UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
